version: '3.8'

services:
  core-api:
    # Mount source code for Hot Reloading
    volumes:
      - ./backend/core-api/src:/app/src
      - ./backend/core-api/package.json:/app/package.json
    env_file:
      - ./backend/core-api/.env.docker
    command: npm run dev

  proxy-service:
    volumes:
      - ./backend/proxy-service:/app
    environment:
      - ENV=development

  mongo:
    ports:
      - "27017:27017"